// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XMS.Infrastructure.Data;

#nullable disable

namespace XMS.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414085337_RenameToCatalog_СтатьяДДС_Key")]
    partial class RenameToCatalog_СтатьяДДС_Key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BitrixId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("LastName")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeBuhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeZupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("OperationalManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAdId")
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("UserUtId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeBuhId");

                    b.HasIndex("EmployeeZupId");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationManagerId");

                    b.HasIndex("OperationalManagerId");

                    b.HasIndex("UserAdId");

                    b.HasIndex("UserUtId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.EmployeeBuh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EmployeesBuh", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.EmployeeZup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EmployeesZup", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("JobTitles", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.UserAd", b =>
                {
                    b.Property<string>("Sid")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DistinguishedName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Manager")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Sid");

                    b.ToTable("UsersAd", (string)null);
                });

            modelBuilder.Entity("XMS.Domain.Models.UserUt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("UsersUt", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Catalog_КонтактныеЛицаПартнеров_Feature.Catalog_КонтактныеЛицаПартнеров", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Owner_Key")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Catalog_КонтактныеЛицаПартнеров", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Catalog_Контрагенты_Feature.Catalog_Контрагенты", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Catalog_Контрагенты", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Catalog_Номенклатура_Feature.Catalog_Номенклатура", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<Guid>("Parent_Key")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Catalog_Номенклатура", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Catalog_Партнеры_Feature.Catalog_Партнеры", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Parent_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("БизнесРегион_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ДатаРегистрации")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Клиент")
                        .HasColumnType("bit");

                    b.Property<string>("Комментарий")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("Конкурент")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ОсновнойМенеджер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Перевозчик")
                        .HasColumnType("bit");

                    b.Property<bool>("Поставщик")
                        .HasColumnType("bit");

                    b.Property<bool>("ПрочиеОтношения")
                        .HasColumnType("bit");

                    b.Property<string>("ЮрФизЛицо")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Catalog_Партнеры", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Catalog_Пользователи_Feature.Catalog_Пользователи", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Catalog_Пользователи", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Catalog_СтатьиДвиженияДенежныхСредств_Feature.Catalog_СтатьиДвиженияДенежныхСредств", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Parent_Key")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Catalog_СтатьиДвиженияДенежныхСредств", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_ЗаказКлиента_Feature.Document_ЗаказКлиента", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Склад_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("СуммаДокумента")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Document_ЗаказКлиента", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_РасходныйКассовыйОрдер_Feature.Document_РасходныйКассовыйОрдер", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Автор_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Валюта_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Выдать")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Договор")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Договор_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ДокументОснование")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ДокументОснование_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ЗаявкаНаРасходованиеДенежныхСредств")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ЗаявкаНаРасходованиеДенежныхСредств_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("КСЗ_КатегорияЗатрат_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Комментарий")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("Контрагент_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("НалогообложениеНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("НаправлениеДеятельности_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ОбъектРасчетов_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Организация_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Основание")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ПоДокументу")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Подразделение_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Приложение")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("СтатьяДвиженияДенежныхСредств_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("СуммаДокумента")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Document_РасходныйКассовыйОрдер", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_РасходныйКассовыйОрдер_Feature.Document_РасходныйКассовыйОрдер_РасшифровкаПлатежа", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ВалютаВзаиморасчетов_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ЗаявкаНаРасходованиеДенежныхСредств")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ЗаявкаНаРасходованиеДенежныхСредств_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Комментарий")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("НаправлениеДеятельности_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ОбъектРасчетов_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Организация_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Подразделение_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтавкаНДС_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтатьяДвиженияДенежныхСредств_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтатьяРасходов")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("СтатьяРасходов_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Сумма")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("СуммаВзаиморасчетов")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("СуммаНДС")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Ref_Key", "LineNumber");

                    b.ToTable("1c_ut_Document_РасходныйКассовыйОрдер_РасшифровкаПлатежа", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_РеализацияТоваровУслуг_Feature.Document_РеализацияТоваровУслуг", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Склад_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("СуммаДокумента")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Document_РеализацияТоваровУслуг", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_СписаниеБезналичныхДенежныхСредств_Feature.Document_СписаниеБезналичныхДенежныхСредств", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataVersion")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Автор_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Валюта_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Договор")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Договор_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ДокументОснование")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ДокументОснование_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ЗаявкаНаРасходованиеДенежныхСредств")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ЗаявкаНаРасходованиеДенежныхСредств_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("КСЗ_КатегорияЗатрат_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Комментарий")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("Контрагент_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("НазначениеПлатежа")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("НалогообложениеНДС")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("НаправлениеДеятельности_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ОбъектРасчетов_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Организация_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Подразделение_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтатьяДвиженияДенежныхСредств_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("СуммаДокумента")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ХозяйственнаяОперация")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ref_Key");

                    b.ToTable("1c_ut_Document_СписаниеБезналичныхДенежныхСредств", (string)null);
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_СписаниеБезналичныхДенежныхСредств_Feature.Document_СписаниеБезналичныхДенежныхСредств_РасшифровкаПлатежа", b =>
                {
                    b.Property<Guid>("Ref_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ВалютаВзаиморасчетов_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ЗаявкаНаРасходованиеДенежныхСредств")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ЗаявкаНаРасходованиеДенежныхСредств_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Комментарий")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("Контрагент_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("НаправлениеДеятельности_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ОбъектРасчетов_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Партнер_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Подразделение_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтавкаНДС_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтатьяДвиженияДенежныхСредств_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("СтатьяРасходов")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("СтатьяРасходов_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Сумма")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("СуммаВзаиморасчетов")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("СуммаНДС")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Ref_Key", "LineNumber");

                    b.ToTable("1c_ut_Document_СписаниеБезналичныхДенежныхСредств_РасшифровкаПлатежа", (string)null);
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCatalog_ДДС", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Catalog_СтатьяДДС_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CostCategoryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CostCategoryItemId");

                    b.ToTable("CostCatalog_ДДС", (string)null);
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ParentId");

                    b.ToTable("CostCategories", (string)null);
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCategoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("CostCategoryItems", (string)null);
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CostItems", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("XMS.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("XMS.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XMS.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("XMS.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMS.Domain.Models.Department", b =>
                {
                    b.HasOne("XMS.Domain.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("XMS.Domain.Models.Employee", b =>
                {
                    b.HasOne("XMS.Domain.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.EmployeeBuh", "EmployeeBuh")
                        .WithMany()
                        .HasForeignKey("EmployeeBuhId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.EmployeeZup", "EmployeeZup")
                        .WithMany()
                        .HasForeignKey("EmployeeZupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.Employee", "LocationManager")
                        .WithMany()
                        .HasForeignKey("LocationManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XMS.Domain.Models.Employee", "OperationalManager")
                        .WithMany()
                        .HasForeignKey("OperationalManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XMS.Domain.Models.UserAd", "UserAd")
                        .WithMany()
                        .HasForeignKey("UserAdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XMS.Domain.Models.UserUt", "UserUt")
                        .WithMany()
                        .HasForeignKey("UserUtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Department");

                    b.Navigation("EmployeeBuh");

                    b.Navigation("EmployeeZup");

                    b.Navigation("JobTitle");

                    b.Navigation("Location");

                    b.Navigation("LocationManager");

                    b.Navigation("OperationalManager");

                    b.Navigation("UserAd");

                    b.Navigation("UserUt");
                });

            modelBuilder.Entity("XMS.Domain.Models.Location", b =>
                {
                    b.HasOne("XMS.Domain.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_РасходныйКассовыйОрдер_Feature.Document_РасходныйКассовыйОрдер_РасшифровкаПлатежа", b =>
                {
                    b.HasOne("XMS.Integration.OneC.Ut.Features.Document_РасходныйКассовыйОрдер_Feature.Document_РасходныйКассовыйОрдер", null)
                        .WithMany("РасшифровкаПлатежа")
                        .HasForeignKey("Ref_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_СписаниеБезналичныхДенежныхСредств_Feature.Document_СписаниеБезналичныхДенежныхСредств_РасшифровкаПлатежа", b =>
                {
                    b.HasOne("XMS.Integration.OneC.Ut.Features.Document_СписаниеБезналичныхДенежныхСредств_Feature.Document_СписаниеБезналичныхДенежныхСредств", null)
                        .WithMany("РасшифровкаПлатежа")
                        .HasForeignKey("Ref_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCatalog_ДДС", b =>
                {
                    b.HasOne("XMS.Modules.CostModule.Domain.CostCategoryItem", "CostCategoryItem")
                        .WithMany()
                        .HasForeignKey("CostCategoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostCategoryItem");
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCategory", b =>
                {
                    b.HasOne("XMS.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XMS.Domain.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XMS.Modules.CostModule.Domain.CostCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCategoryItem", b =>
                {
                    b.HasOne("XMS.Modules.CostModule.Domain.CostCategory", "Category")
                        .WithMany("CategoryItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XMS.Modules.CostModule.Domain.CostItem", "Item")
                        .WithMany("CategoryItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("XMS.Domain.Models.Department", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_РасходныйКассовыйОрдер_Feature.Document_РасходныйКассовыйОрдер", b =>
                {
                    b.Navigation("РасшифровкаПлатежа");
                });

            modelBuilder.Entity("XMS.Integration.OneC.Ut.Features.Document_СписаниеБезналичныхДенежныхСредств_Feature.Document_СписаниеБезналичныхДенежныхСредств", b =>
                {
                    b.Navigation("РасшифровкаПлатежа");
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostCategory", b =>
                {
                    b.Navigation("CategoryItems");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("XMS.Modules.CostModule.Domain.CostItem", b =>
                {
                    b.Navigation("CategoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
